# serverless.yml

service: dev-tools

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []

package:
  exclude:
    - node_modules/**
    - env/**

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: src.main.handler
    events:
      - http: ANY /
        cors: true
      - http: "ANY {proxy+}"
        cors: true
